# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0afb29e0087e422c6d70d87230990118f4d58529f5ed14fbdc31b1361d2dc661c70368fe64ab3ec506f1cef3fdc562bdad90798bcc56f623d5cca67ad0210588

test:
  secret_key_base: bdacf70e21d8f9fe198d2ca244dca507948f8b3b13c9693584940f064d4e771c6ca009839d8e45ff065fa582850ed9ec8a82b55f7e89dc59c148ac3ee687f67b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
